version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_rest_db
    ports:
        - 5432:5432

  db-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
        - 9090:80
    depends_on:
        - db
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin
        PGADMIN_DEFAULT_PASSWORD: admin
